### ISSUE TITLE
installation path linux

### ISSUE THREAD

**Issue by BaumiCoder** [ceever/Radio-Browser.info.lua#2]
I installed the plugin on my Linux Mint PC. There was no /usr/lib/vlc/lua/ so I created vlc and lua folder, but VLC don't get the new plugin. I found out that the plugins of my VLC are at /usr/lib/x86_64-linux-gnu/vlc/lua .

I am not sure if this is the new normal folder for plugins on linux VLC or only on my distribution.

**Comment by ceever** [comment]
Thanks, adjusted it accordingly. 👍

**Comment by ceever** [comment]
Apparently, I decided against adjusting this ... stupid me. 🤦 You are indeed right! 👍 I don't quite understand this share and lib directory structure, but /usr/lib/vlc/lua/ is indeed causing VLC to fail.

Will adjust.
