### ISSUE TITLE
Add to videolan Pluginstore

### ISSUE THREAD

**Issue by BaumiCoder** [ceever/Radio-Browser.info.lua#3]
In VLC there is an integrated "store" for plugins. You can browse that store in VLC here: Tools - Plugins and extensions (Englisch) / Werkzeuge / Plugins und Erweiterung (German, the language of my vlc installation).
Im not completely sure, but I think this store in the web should be the one at [addons.videolan.org](https://addons.videolan.org). At [api.addons.videolan.org](https://api.addons.videolan.org) there can be found a Login / Register for addons developer. I think there can developers can upload new plugin, but I can't find any documentation about uploading new plugins for the VLC plugin store.

**Comment by ceever** [comment]
This store seems badly supported and a tiny userbase. Hence, the extra effort is not worth it. People coming from radio-browser.info have the addon mentioned on the website. It's sad that vlc isnt that great in marketing.
