### ISSUE TITLE
ex_Radio_Browser_info.lua doesn´t start under VLC with W10

### ISSUE THREAD

**Issue by djsoftware50** [ceever/Radio-Browser.info.lua#5]
I use Windows 10 22H2 19045.2486 and VLC 3.0.18 Vetinari.

The search extension doesn´t start and no appear in the view menu.
I analized file and update the -- Parse CSV line -- section with the info page http://lua-users.org/wiki/LuaCsv, tested it and run ok.

PD Sorry, my english is not good.

**Comment by NJT145** [comment]
What you mean is that it doesn't show Radio-Browser as extension, right? I get the same issue.

**Comment by NJT145** [comment]
What is the error that you get? Can you describe it? I have time to debug it, and I am willing to help.

**Comment by djsoftware50** [comment]
Hi:

That´s correct

De: Nejat ***@***.***>
Enviado: jueves, 2 de febrero de 2023 10:20 a. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [ceever/Radio-Browser.info.lua] ex_Radio_Browser_info.lua doesn´t start under VLC with W10 (Issue #5)


What you mean is that it doesn't show Radio-Browser as extension, right? I get the same issue.

**Comment by djsoftware50** [comment]
Hi:

I copied the extension file to the corresponding directory -ex_Radio_Browser_info.lua- but the option in the view menu -(Radio-Browser.info (Search)- does not appear.

Inside the LUA file I deleted the function -function ParseCSVLine- and replaced it with the one from the web page http://lua-users.org/wiki/LuaCsv.

With this change the extension worked.

Daniel

De: Nejat ***@***.***>
Enviado: jueves, 2 de febrero de 2023 10:22 a. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [ceever/Radio-Browser.info.lua] ex_Radio_Browser_info.lua doesn´t start under VLC with W10 (Issue #5)


What is the error that you get? Can you describe it? I have time to debug it, and I am willing to help.

**Comment by NJT145** [comment]
I made a pull request at #6 . This will work while keeping modified `pos = pos + 1` fix.

**Comment by djsoftware50** [comment]
> I made a pull request at #6 . This will work while keeping modified `pos = pos + 1` fix.

Thanks @NJT145 👍

**Comment by ceever** [comment]
So, if I understand correctly then the "continue" behaviour is not supported by this specific combination of Windows and VLC. Which is why the extension is not loaded in VLC.

However, the proposed code correction will fail whenever the proposed handling of incomplete quotes occurs. One cannot write "if not endp then" and later after conclusion of the "if" continue using "endp" in this statement "pos = endp + 1" ... eventually this will fail.

@NJT145 Do you agree?

I will see how to circumvent this problem.

**Comment by ceever** [comment]
@djsoftware50 I have just updated ex_Radio_Browser_info.lua (v0.61):
https://github.com/ceever/Radio-Browser.info.lua/blob/main/ex_Radio_Browser_info.lua

Could you check whether the extension is working/available under your W10/VLC in "View" of VLC?

Many thanks ...

**Comment by djsoftware50** [comment]
@ceever I tested the extension, run ok

Thanks😊

**Comment by NJT145** [comment]
I guess that your "continue" stuff wasn't working because it is in the "repeat" loop.
Thanks for latest fix. It's working well.
