### ISSUE TITLE
Linux behaviour difference between global and user share directories

### ISSUE THREAD

**Issue by couladin** [ceever/Radio-Browser.info.lua#7]
Discovered a difference in behaviour between installing these Lua scripts under `/usr/share/vlc/lua/` and `~/.local/share/vlc/lua/` in Linux Ubuntu 23.04 using VLC 3.0.18-2build1 (called "3.0.18 Vetinari" inside VLC; the current version from APT).

If I place the scripts into their respective subdirectories under /usr/share/vlc/lua/ (as root), when I open VLC and double-click one of the "titles" (By codec, By tag, etc), instead off expanding that top-level branch it seems to quickly cycle down from that entry down to the bottom of the list (By codec, by default), shows the player progress bar cycling for a few seconds, then does nothing. 

The "By codec" branch can be expanded to the next level down (MP3, AAC, etc), but can't be opened/expanded any further.

But if I place the scripts into their respective subdirectories under ~/.local/share/vlc/lua/ (as my user), everything works correctly.

Flagging it here in case something has broken the global Linux install option.

**Comment by ceever** [comment]
Looks like when placing them under /usr/share/vlc/lua/, vlc cannot find necessary libraries anymore.

You might have to place everything under: /usr/lib/x86_64-linux-gnu/vlc/lua/ ... this seem to work for me. Someone mentioned this in the past, weirdly enough.

I will adjust the documentation accordingly.

Thanks 🙏

**Comment by ceever** [comment]
Done! That was quicker than I thought 🤝
